# -*- coding: utf-8 -*-
"""lineregr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJjcZt5oWlWwNY8UjP1bg3XyBvwm1etY
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('pos_sal.csv')
df=pd.read_csv('http://13.234.66.67/summer19/datasets/salary.csv')

exp =  df.iloc[:,0:1].values

df.info()

sal = df.iloc[:,1:].values

plt.xlabel("experience")
plt.ylabel("salary")
plt.scatter(exp,sal)
plt.show()

from sklearn.linear_model import LinearRegression

regr = LinearRegression()

trained = regr.fit(exp,sal)

plt.xlabel("experience")
plt.ylabel("salary")
plt.scatter(exp,sal,label = "actual data as per exp")
plt.plot(exp,trained.predict(exp),label = "prediction salary")
plt.legend()
plt.show()

